config/routes.rb
Rails.application.routes.draw do
  resources :users
  root :to => redirect("/users")

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_history, :dependent => :destroy
end

app/models/user_history.rb
class UserHistory < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    if params[:timestamp]
      params[:timestamp] = Time.at(params[:timestamp].to_i)
      @user_histories = UserHistory.where(:user_id => params[:id]).where(:created_at => params[:timestamp])
    else   
      @user_histories = UserHistory.where(:user_id => params[:id])
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user_history = UserHistory.new(user_params)
    @user_history.version_no = 1
    @user.user_history.push @user_history
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        @last_revision_no = UserHistory.where(:user_id => params[:id]).last(1)[0].version_no
        user_history = UserHistory.new(user_params)
        user_history.version_no = @last_revision_no + 1
        user_history.user_id = params[:id]
        user_history.save  
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      permitted = params.require(:user).permit(:name, :total_amount, :paid_amount)
      permitted
    end
end
#params.require(:user).permit(:name, :total_amount, :paid_amount)

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.text_field "name", :placeholder => "Enter Name" %> 
  <%= f.text_field "total_amount", "size" => 5, :placeholder => "Enter total amount" %> 
  <%= f.text_field "paid_amount", "size" => 5, :placeholder => "Enter paid amount" %>   
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      </tr>
          <td><%= user.id %></td> 
          <td><%= user.name %></td>
          <td><%= user.total_amount %></td>
          <td><%= user.paid_amount %></td>  
      </tr>
      <tr>
          <td><%= link_to 'Show', user %></td>
          <td><a href="/users/<%= user.id %>?timestamp=1440568980">Filter By Time</a></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div><h4>Name:</h4> <b><%= @user.name %></b></div>
<div><h4>Total Amount:</h4> <b><%= @user.total_amount %></b></div>
<div><h4>Paid Amount:</h4> <b><%= @user.paid_amount %></b></div> 

  <% if params[:timestamp] %> 
    <% if @user_histories %>
    <br><br>
      <b>User Payment Histories</b>
        <% if @user_histories[0] %>
          <table>
            <thead>
              <th>Name</th>
              <th>Total Amount</th>
              <th>Paid Amount</th>        
            </thead>
            <tbody> 	
              <% @user_histories.each do |data| %>
                <tr>
                  <td><%= data.name %></td>
                  <td><%= data.total_amount %></td>
                  <td><%= data.paid_amount %></td>              
                </tr>	
              <% end %>
            </tbody>
          </table>  
        <% else %>
           <h3 style="color:red">No histories in this time</h3> 
        <% end %>  
    <% end %>  
  <% end %>  


<%= link_to 'Edit', edit_user_path(@user) %> 
<%= link_to 'Back', users_path %>